# SentimentSignal v5.0 - Configuration
version: "5.0"
phase: "0_validation"
environment: "paper"

# TRADING
funds_per_trade: 300
max_concurrent_positions: 5
max_positions_per_ticker_per_day: 1

# STATION 2: PRE-SCREEN
prescreen:
  iv_rank_threshold: 50
  min_open_interest: 500
  max_bid_ask_spread_pct: 10
  min_delta: 0.30
  max_delta: 0.75
  earnings_buffer_days: 2
  min_daily_volume: 1000000

# STATION 3: SCORING
scoring:
  weights:
    sentiment: 40
    technical: 45
    options_flow: 15
  
  thresholds:
    sentiment: 85
    technical: 75
    options_flow: 70
    pump_risk: 50
  
  consensus_required: 3
  alignment_multiplier: 1.3
  
  conviction_tiers:
    extreme: 95
    high: 85
    moderate: 75

# STATION 4: SIZING
sizing:
  conviction_multipliers:
    EXTREME: 1.5
    HIGH: 1.0
    MODERATE: 0.6
    LOW: 0.0
  
  max_portfolio_delta: 8.0
  max_portfolio_gamma: 10.0
  max_positions_per_sector: 2

# STATION 6: EXITS
exits:
  breakeven_trigger_pct: 20
  trail_method: "atr"
  atr_multiplier: 2.0
  psar_enabled: true
  rsi_hook_enabled: true
  rsi_hook_threshold: 70
  max_hold_days: 5

# RISK
risk:
  daily_loss_limit_pct: 10
  max_consecutive_losses: 3
  auto_blacklist: true
  blacklist_duration_days: 30

# DATA SOURCES
data:
  reddit:
    client_id: "YOUR_REDDIT_CLIENT_ID"
    client_secret: "YOUR_REDDIT_SECRET"
    user_agent: "SentimentSignal/1.0"
  
  stocktwits:
    access_token: "YOUR_STOCKTWITS_TOKEN"
  
  ibkr:
    host: "127.0.0.1"
    port: 7497
    client_id: 1

# LOGGING
logging:
  level: "INFO"
  log_decisions: true
  export_trades: true
